version: 2.1
jobs:
  build:
    executor:
      name: python/default  # Choose the appropriate Python executor
    steps:
      - checkout  # Check out your repository
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
